### ISSUE TITLE
request the command line for basic analysis of TCR

### ISSUE THREAD

**Issue by decenwang** [penuts7644/TcrDataComparison#1]
Hi Penuts,

Could you please share with me your basic command lines of IGoR, which includes the 3 models. I am a rookie in bioinformatics. I would like to use IGoR to analyze! and I found you talked a lot with Qmarcou. I would like to follow your codes, cause you know for a beginner, I cannot understand some of the command lines on the github of IGoR. Thanks a lot!

Kindest,

Decen

**Comment by penuts7644** [comment]
Hi Decen,

Sure, what would you exactly like to know for IGoR? I can give you some general info on how the IGoR pipeline works if you want? Also have a look at my other repo [ImmunoProbs](https://github.com/penuts7644/ImmunoProbs). That one I actively work on and is meant as a wrapped around IGoR and CDR3 counterpart (OLGA). The documentation is on the wiki page for the repo.

What I understand from Quentin is that he himself is not doing the development of IGoR anymore. So you'll have to work around IGoR's and OLGA's weird issues to make them work.

Cheers, Wout
